version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:15-3.3
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:latest
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    restart: always
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '44444-5ea1-5996-xxxx-rrrrr'
      SECRET: 'xxxxx-cda1-yyyy-b5b5-oooooo'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'example@admin.com'
      ADMIN_PASSWORD: 'wonderful'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'
  client:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT = 3000
      - NODE_ENV = development
      - PUBLIC_DIRECTUS_URL=http://directus:8055
      - DIRECTUS_STATIC_TOKEN=YGq_QnAy_k-34567890
      - PUBLIC_ASSETS_URL = 'http://0.0.0.0:8055' 
    networks:
      - directus
    

networks:
  directus:
volumes:
    postgres:
    uploads: